In [3]:
import pandas as pd
from io import StringIO

In [4]:
csv_data = '''A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
10.0, 11.0, 12.0,
'''
df = pd.read_csv(StringIO(csv_data))

In [5]:
df

      A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [6]:
df.isnull().sum()

A    0
B    0
C    1
D    1
dtype: int64

In [18]:
df_test = df.copy()

In [13]:
df_test = df_test.dropna(axis=1)
df_test

      A     B
0   1.0   2.0
1   5.0   6.0
2  10.0  11.0

In [15]:
df_test = df_test.dropna(how='all')
df_test

      A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [17]:
df_test = df_test.dropna(thresh=4)
df_test

     A    B    C    D
0  1.0  2.0  3.0  4.0

In [20]:
df_test = df_test.dropna(subset=['C'])
df_test

      A     B     C    D
0   1.0   2.0   3.0  4.0
2  10.0  11.0  12.0  NaN